#!/usr/bin/env bash
#
# Local end-to-end test of the Slingslop Ansible deployment against a throwaway
# Ubuntu 26.04 VM (Vagrant + VirtualBox). It runs the *real* bootstrap.yml and
# site.yml — the only differences from prod are supplied via local/vars.local.yml
# (local domain, self-signed TLS, throwaway secrets).
#
# Usage:
#   ./test-local.sh up         # boot VM + run bootstrap + site (default)
#   ./test-local.sh bootstrap  # (re)run bootstrap.yml only
#   ./test-local.sh site       # (re)run site.yml only
#   ./test-local.sh hosts      # print the /etc/hosts lines you need
#   ./test-local.sh ssh        # ssh into the VM as the deploy user
#   ./test-local.sh status     # vagrant status
#   ./test-local.sh destroy    # tear the VM down
#
# Env overrides: SLINGSLOP_VM_IP, SLINGSLOP_VM_MEM, SLINGSLOP_VM_CPUS
set -euo pipefail

LOCAL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ANSIBLE_DIR="$(cd "${LOCAL_DIR}/.." && pwd)"
VM_IP="${SLINGSLOP_VM_IP:-192.168.56.50}"
DEPLOY_USER="deploy"
RUNTIME_DIR="${LOCAL_DIR}/.runtime"
SSH_DIR="${LOCAL_DIR}/.ssh"
VENV_DIR="${LOCAL_DIR}/.venv"
DEPLOY_KEY="${SSH_DIR}/deploy_ed25519"
SECRETS_VARS="${RUNTIME_DIR}/secrets.local.yml"
BOOTSTRAP_INV="${RUNTIME_DIR}/bootstrap-inventory.ini"
DEPLOY_INV="${RUNTIME_DIR}/deploy-inventory.ini"

MAIN_VARS="${ANSIBLE_DIR}/inventory/group_vars/all/main.yml"
LOCAL_VARS="${LOCAL_DIR}/vars.local.yml"

# Domains that must resolve to the VM for Traefik host-routing to work.
HOST_NAMES=("slingslop.local" "www.slingslop.local" "editor.slingslop.local" "grafana.slingslop.local" "logs.slingslop.local" "traefik.slingslop.local")

log()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[!]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[x]\033[0m %s\n' "$*" >&2; exit 1; }

require() { command -v "$1" >/dev/null 2>&1 || die "'$1' not found on PATH. $2"; }

ensure_prereqs() {
  require vagrant "Install Vagrant."
  require VBoxManage "Install VirtualBox."
  require python3 "Install python3 (+ python3-venv)."
  mkdir -p "${RUNTIME_DIR}" "${SSH_DIR}"
}

ensure_venv() {
  # Rebuild if the venv is missing OR half-installed (e.g. an interrupted pip
  # run can leave ansible-playbook present but passlib's files/METADATA missing,
  # which later crashes gen_secrets with "No module named 'passlib.hash'").
  if [[ ! -x "${VENV_DIR}/bin/ansible-playbook" ]] \
     || ! "${VENV_DIR}/bin/python" -c "import passlib.hash" >/dev/null 2>&1; then
    [[ -d "${VENV_DIR}" ]] && warn "venv missing/incomplete — rebuilding from scratch."
    rm -rf "${VENV_DIR}"
    log "Creating Python venv + installing ansible-core, passlib …"
    python3 -m venv "${VENV_DIR}" \
      || die "Could not create venv. Install python3-venv (e.g. apt install python3-venv)."
    "${VENV_DIR}/bin/pip" install --quiet --upgrade pip
    "${VENV_DIR}/bin/pip" install --quiet "ansible-core>=2.16" passlib
  fi
  export PATH="${VENV_DIR}/bin:${PATH}"
  if ! ansible-galaxy collection list 2>/dev/null | grep -q community.docker; then
    log "Installing required Ansible collections …"
    ansible-galaxy collection install -r "${ANSIBLE_DIR}/requirements.yml" >/dev/null
  fi
}

ensure_ssh_key() {
  if [[ ! -f "${DEPLOY_KEY}" ]]; then
    log "Generating throwaway deploy SSH key …"
    ssh-keygen -t ed25519 -N "" -C "slingslop-local-deploy" -f "${DEPLOY_KEY}" >/dev/null
  fi
}

gen_secrets() {
  # Valid apr1 (MD5) htpasswd, pure-python via passlib → Traefik basicAuth-compatible.
  # user = password = "localtest".
  local htpasswd
  htpasswd="$("${VENV_DIR}/bin/python" - <<'PY'
from passlib.hash import apr_md5_crypt
print("localtest:" + apr_md5_crypt.hash("localtest"))
PY
)"
  cat > "${SECRETS_VARS}" <<EOF
---
# Generated by test-local.sh — user+password are both "localtest".
vault_editor_basicauth_users_htpasswd: |
  ${htpasswd}
vault_grafana_basicauth_users_htpasswd: |
  ${htpasswd}
vault_traefik_dashboard_htpasswd: |
  ${htpasswd}
EOF
  # GHCR pull credentials for the private slingslop/webcache images.
  # Set via env so the token never lands in a committed file:
  #   export GHCR_USER=<github-user>
  #   export GHCR_TOKEN=<PAT with read:packages>
  if [[ -n "${GHCR_TOKEN:-}" ]]; then
    cat >> "${SECRETS_VARS}" <<EOF
vault_ghcr_pull_user: "${GHCR_USER:-}"
vault_ghcr_pull_token: "${GHCR_TOKEN}"
EOF
    log "GHCR credentials picked up from env (user: ${GHCR_USER:-<unset>})."
  else
    warn "GHCR_TOKEN not set — private images (slingslop, webcache) will fail to pull."
    warn "  export GHCR_USER=<github-user>; export GHCR_TOKEN=<PAT read:packages>; then re-run."
  fi
}

write_inventories() {
  # Bootstrap connection: as the vagrant user (passwordless sudo) via its
  # NAT-forwarded SSH, parsed from `vagrant ssh-config`.
  local ssh_cfg host port keyfile
  ssh_cfg="$(cd "${LOCAL_DIR}" && vagrant ssh-config 2>/dev/null)" \
    || die "VM not running. Run: ./test-local.sh up"
  host="$(awk '/^[[:space:]]*HostName /   {print $2; exit}' <<<"${ssh_cfg}")"
  port="$(awk '/^[[:space:]]*Port /       {print $2; exit}' <<<"${ssh_cfg}")"
  keyfile="$(awk '/^[[:space:]]*IdentityFile / {print $2; exit}' <<<"${ssh_cfg}")"

  local common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes"

  cat > "${BOOTSTRAP_INV}" <<EOF
[slingslop]
slingslop-local ansible_host=${host} ansible_port=${port} ansible_user=vagrant ansible_ssh_private_key_file=${keyfile} ansible_ssh_common_args='${common_args}'
EOF

  cat > "${DEPLOY_INV}" <<EOF
[slingslop]
slingslop-local ansible_host=${VM_IP} ansible_port=22 ansible_user=${DEPLOY_USER} ansible_ssh_private_key_file=${DEPLOY_KEY} ansible_ssh_common_args='${common_args}'
EOF
}

run_play() {  # $1 = inventory, $2 = playbook
  # Override the repo's stdout_callback=yaml: that callback moved out of
  # community.general (removed in 12.0). Use core's default+yaml formatting.
  ( cd "${ANSIBLE_DIR}" \
    && ANSIBLE_HOST_KEY_CHECKING=False \
       ANSIBLE_STDOUT_CALLBACK=default \
       ANSIBLE_CALLBACK_RESULT_FORMAT=yaml \
       ansible-playbook -i "$1" "playbooks/$2" \
         -e "@${MAIN_VARS}" -e "@${LOCAL_VARS}" -e "@${SECRETS_VARS}" )
}

cmd_up() {
  ensure_prereqs; ensure_venv; ensure_ssh_key; gen_secrets
  log "Booting VM (vagrant up) …"
  ( cd "${LOCAL_DIR}" && vagrant up )
  write_inventories
  log "Running bootstrap.yml (as vagrant → creates deploy user, hardens SSH) …"
  run_play "${BOOTSTRAP_INV}" bootstrap.yml
  log "Running site.yml (as deploy → full stack) …"
  run_play "${DEPLOY_INV}" site.yml
  cmd_hosts
  log "Done. Add the /etc/hosts lines above, then browse (accept the self-signed cert):"
  echo "     https://www.slingslop.local/     (public site)"
  echo "     https://editor.slingslop.local/  (basicAuth: localtest / localtest, then Sling admin)"
  echo "     https://grafana.slingslop.local/ (basicAuth: localtest / localtest)"
  echo "     https://traefik.slingslop.local/ (basicAuth: localtest / localtest)"
}

cmd_bootstrap() { ensure_prereqs; ensure_venv; ensure_ssh_key; gen_secrets; write_inventories; run_play "${BOOTSTRAP_INV}" bootstrap.yml; }
cmd_site()      { ensure_prereqs; ensure_venv; ensure_ssh_key; gen_secrets; write_inventories; run_play "${DEPLOY_INV}" site.yml; }

cmd_hosts() {
  log "Add these lines to /etc/hosts on your host machine:"
  echo
  echo "    ${VM_IP} ${HOST_NAMES[*]}"
  echo
  echo "  (e.g.:  echo '${VM_IP} ${HOST_NAMES[*]}' | sudo tee -a /etc/hosts )"
}

cmd_ssh()     { ensure_ssh_key; ssh -i "${DEPLOY_KEY}" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${DEPLOY_USER}@${VM_IP}"; }
cmd_status()  { ( cd "${LOCAL_DIR}" && vagrant status ); }
cmd_destroy() { ( cd "${LOCAL_DIR}" && vagrant destroy -f ); rm -rf "${RUNTIME_DIR}"; log "VM destroyed. (SSH key + venv kept under local/.ssh, local/.venv)"; }

main() {
  case "${1:-up}" in
    up)        cmd_up ;;
    bootstrap) cmd_bootstrap ;;
    site)      cmd_site ;;
    hosts)     cmd_hosts ;;
    ssh)       cmd_ssh ;;
    status)    cmd_status ;;
    destroy)   cmd_destroy ;;
    *) die "Unknown command '$1'. Use: up | bootstrap | site | hosts | ssh | status | destroy" ;;
  esac
}

main "$@"
