#!/usr/bin/env bash
# Writes the (gitignored) prod inventory + host_vars from CI env vars so the
# deploy jobs have something to target. Run from ops/ansible as the CWD.
#
#   DEPLOY_HOST    SSH target / public IP of the VPS   (e.g. motorbrot.org)
#   DEPLOY_DOMAIN  public domain published by Traefik   (e.g. motorbrot.org)
#   VAULT_PASS     (optional) ANSIBLE_VAULT_PASSWORD secret — when set, writes
#                  a plaintext vault.yml so Ansible never has to decrypt a
#                  committed encrypted copy (fixes the vault-password mismatch
#                  that occurs after a vault rekey).
set -euo pipefail

: "${DEPLOY_HOST:?DEPLOY_HOST not set}"
: "${DEPLOY_DOMAIN:?DEPLOY_DOMAIN not set}"

mkdir -p inventory/host_vars

cat > inventory/hosts.yml <<YAML
---
all:
  hosts:
    slingslop-prod:
      ansible_host: ${DEPLOY_HOST}
      ansible_user: deploy
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python3
  children:
    slingslop:
      hosts:
        slingslop-prod: {}
YAML

cat > inventory/host_vars/slingslop-prod.yml <<YAML
---
domain: ${DEPLOY_DOMAIN}
editor_allowlist_cidrs: []
YAML

# When VAULT_PASS is provided (CI mode), write a plaintext vault.yml so that
# Ansible loads it instead of any encrypted copy committed to the repository.
# This prevents "Decryption failed (no vault secrets were found)" errors that
# occur when vault.yml was re-encrypted with a password that differs from the
# ANSIBLE_VAULT_PASSWORD secret (e.g., after a vault rekey).
# vault_sling_admin_password is set to the same value so the rotate-password
# task idempotently asserts the expected admin credential on every deploy.
if [ -n "${VAULT_PASS:-}" ]; then
  mkdir -p inventory/group_vars/all
  # Use Python for safe YAML serialisation — handles any character in VAULT_PASS.
  python3 - <<EOF > inventory/group_vars/all/vault.yml
import os, json, sys
pw = os.environ['VAULT_PASS']
sys.stdout.write('---\n# Generated by write-inventory.sh — never committed.\nvault_sling_admin_password: ' + json.dumps(pw) + '\n')
EOF
fi

echo "Wrote inventory for host=${DEPLOY_HOST} domain=${DEPLOY_DOMAIN}"
