#!/bin/sh -eu
echo '-------------------------------------------------------------------------------------------'
echo '[NOTE] Launching application, this will fail if you did not build the project at least once'
echo '[NOTE] Remove the launcher folder to throw away local changes'
echo '-------------------------------------------------------------------------------------------'

# Optional Felix HTTP JVM opts (e.g. virtual threads) from the CONGA local-plain
# environment. Generated by `mvn -pl devops/conga conga:generate`; absent = fast
# loop with defaults. Same file the Ansible slingslop role appends in prod.
HTTP_JAVA_OPTS=""
CONGA_HTTP_JAVA_OPTS=../devops/conga/target/configuration/local-plain/localhost/env/http-java-opts
[ -f "$CONGA_HTTP_JAVA_OPTS" ] && HTTP_JAVA_OPTS=$(cat "$CONGA_HTTP_JAVA_OPTS")

export JAVA_OPTS="-XX:+UseG1GC -XX:+UseCompactObjectHeaders -XX:+UseStringDeduplication \
                  --enable-native-access=ALL-UNNAMED \
                  -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=38080 \
                  ${EXTRA_JAVA_OPTS:-} ${HTTP_JAVA_OPTS}"

# Sample-content is no longer baked into the feature/seed (code-only). Install
# the staged demo packages once Sling answers — always overwritten (force),
# scoped per content root, so other/user content is untouched. Backgrounded so
# it can wait while the launcher comes up in the foreground. The container/prod
# deploy has no Maven, so it keeps using src/main/container/bin/install-sample-content.sh
# instead; see install-sample-content-local.sh for why the local path differs.
( ./install-sample-content-local.sh ) &

target/dependency/org.apache.sling.feature.launcher/bin/launcher -f target/slingfeature-tmp/feature-slingslop_aggregate.json
